stages:
  - build

test:
  stage: build
  tags:
    - ci
  script:
    - sudo docker info
    - sudo docker build -t myapp ./
    - sudo docker tag myapp gitlab-registry:5000/root/myapp
    - sudo docker push gitlab-registry:5000/root/myapp